runs:
  using: composite
  steps:
  - name: make
    run: make
    shell: bash
  - name: make install
    run: sudo make install
    shell: bash
  - name: check diary version
    run: diary -v
    shell: bash
