name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Install Ubuntu dependencies
      run: apt-get install libcurl4

  build:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: make
      run: make
    - name: make install
      run: make install
    - name: check diary version
      run: diary -v
