name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: make
      run: make
    - name: make install
      run: make install
    - name: check diary version
      run: diary -v

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Install build requirements
      run: sudo apt-get install libncurses5-dev libncursesw5-dev libcurl4-gnutls-dev
    - name: Check out repository
      uses: actions/checkout@v2
    - name: make
      run: make
    - name: make install
      run: make install
    - name: check diary version
      run: diary -v
