name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [macos-latest, ubuntu-18.04, ubuntu-20.04]

    steps:
    - name: make
      run: make
    - name: make check
      run: make check
    - name: check diary version
      run: ./diary -v
