name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: make install
      uses: ./.github/c/make-install

  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Install build requirements
      run: sudo apt-get install libncurses5-dev libncursesw5-dev libcurl4-gnutls-dev
    - name: Check out repository
      uses: actions/checkout@v2
    - name: make install
      uses: ./.github/c/make-install
