name: Man page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  man:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install mandoc
      run: sudo apt-get install mandoc
    - name: Create html from man doc
      run: mandoc -Thtml man1/diary.1 > man1/diary.1.html
    - name: Add ssh key
      env:
        SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      # https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< $(echo "${{ secrets.SSH_B64 }}" | base64 -d)
    - name: Send html to website
      env:
        SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      run: scp -o StrictHostKeyChecking=no man1/diary.1.html hcloud@diary.in0rdr.ch:/home/hcloud/diary-website/man.html
