name: Man page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  man:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install mandoc
      run: sudo apt-get install mandoc
    - name: Create html from man doc
      run: mandoc -Thtml man1/diary.1 > man1/diary.1.html
    - name: Commit new man doc
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add man1/diary.1.html
        git commit -m "refresh diary manpage"
        git push
