name: Man page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SSH_AUTH_SOCK: $RUNNER_TEMP/ssh-agent.sock

jobs:
  man:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install mandoc
      run: sudo apt-get install mandoc
    - name: Create html from man doc
      run: mandoc -Thtml man1/diary.1 > man1/diary.1.html
    - name: Add ssh key
      # https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions
      run: |
        eval "$(ssh-agent -a ${{ env.SSH_AUTH_SOCK }})"
        ls -l $RUNNER_TEMP
        ls -l ${{ env.SSH_AUTH_SOCK }}
        
        ssh-add - <<< "${{ secrets.SSH_B64 }}"
    - name: Send html to website
      run: scp man1/diary.1.html hcloud@diary.in0rdr.ch:/home/hcloud/
